name: 'AppCenter Delete Distributions Github Action'
description: 'Iterates and delete distributions from AppCenter'
inputs:
  distributions:
    description: 'Comma-separated array of distribution IDs to delete, e.g. [24,25,45]'
    required: true
    default: "[]"
  appName:
    description: "App name followed by username e.g. marcelosevergnini-dico/Sample-App"
    required: true
  token:
    description: "Upload token - you can get one from appcenter.ms/settings"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'